-- Catalog generated from the wizard's own amenity lists, so every option a
-- partner can tick has a row here. Codes are a deterministic slug of the
-- label (lowercase, accents stripped, non-alphanumerics to underscore) and
-- the client computes the same slug, so there is no map to keep in sync.
delete from public.partner_application_amenities;
delete from public.partner_amenities;

insert into public.partner_amenities (code, label_fr, applies_to, position) values
  ('wi_fi', 'Wi-Fi', array['guesthouse','hotel','restaurant']::public.partner_type[], 1),
  ('climatisation', 'Climatisation', array['car','guesthouse','hotel','restaurant']::public.partner_type[], 2),
  ('reception_24h_24', 'Réception 24h/24', array['hotel']::public.partner_type[], 3),
  ('ascenseur', 'Ascenseur', array['hotel']::public.partner_type[], 4),
  ('generateur', 'Générateur', array['hotel']::public.partner_type[], 5),
  ('energie_solaire', 'Énergie solaire', array['guesthouse','hotel']::public.partner_type[], 6),
  ('bagagerie', 'Bagagerie', array['hotel']::public.partner_type[], 7),
  ('concierge', 'Concierge', array['hotel']::public.partner_type[], 8),
  ('parking_gratuit', 'Parking gratuit', array['hotel']::public.partner_type[], 9),
  ('parking_payant', 'Parking payant', array['hotel']::public.partner_type[], 10),
  ('voiturier', 'Voiturier', array['hotel']::public.partner_type[], 11),
  ('restaurant', 'Restaurant', array['hotel']::public.partner_type[], 12),
  ('petit_dejeuner', 'Petit-déjeuner', array['guesthouse','hotel']::public.partner_type[], 13),
  ('bar', 'Bar', array['hotel']::public.partner_type[], 14),
  ('room_service', 'Room service', array['hotel']::public.partner_type[], 15),
  ('piscine', 'Piscine', array['guesthouse','hotel']::public.partner_type[], 16),
  ('salle_de_sport', 'Salle de sport', array['hotel']::public.partner_type[], 17),
  ('spa', 'Spa', array['hotel']::public.partner_type[], 18),
  ('massage', 'Massage', array['hotel']::public.partner_type[], 19),
  ('salle_de_reunion', 'Salle de réunion', array['hotel']::public.partner_type[], 20),
  ('salle_de_conference', 'Salle de conférence', array['hotel']::public.partner_type[], 21),
  ('centre_d_affaires', 'Centre d''affaires', array['hotel']::public.partner_type[], 22),
  ('electricite_24h_24', 'Électricité 24h/24', array['guesthouse']::public.partner_type[], 24),
  ('eau_chaude', 'Eau chaude', array['guesthouse']::public.partner_type[], 25),
  ('ventilateurs', 'Ventilateurs', array['guesthouse']::public.partner_type[], 27),
  ('cuisine_partagee', 'Cuisine partagée', array['guesthouse']::public.partner_type[], 29),
  ('cuisine_privee', 'Cuisine privée', array['guesthouse']::public.partner_type[], 30),
  ('refrigerateur', 'Réfrigérateur', array['guesthouse']::public.partner_type[], 31),
  ('micro_ondes', 'Micro-ondes', array['guesthouse']::public.partner_type[], 32),
  ('jardin', 'Jardin', array['guesthouse']::public.partner_type[], 33),
  ('terrasse', 'Terrasse', array['guesthouse','restaurant']::public.partner_type[], 34),
  ('acces_plage', 'Accès plage', array['guesthouse']::public.partner_type[], 36),
  ('barbecue', 'Barbecue', array['guesthouse']::public.partner_type[], 37),
  ('menage', 'Ménage', array['guesthouse']::public.partner_type[], 38),
  ('blanchisserie', 'Blanchisserie', array['guesthouse']::public.partner_type[], 39),
  ('navette_aeroport', 'Navette aéroport', array['guesthouse']::public.partner_type[], 40),
  ('gardien', 'Gardien', array['guesthouse']::public.partner_type[], 42),
  ('cctv', 'CCTV', array['guesthouse']::public.partner_type[], 43),
  ('propriete_cloturee', 'Propriété clôturée', array['guesthouse']::public.partner_type[], 44),
  ('extincteur', 'Extincteur', array['guesthouse']::public.partner_type[], 45),
  ('bluetooth', 'Bluetooth', array['car']::public.partner_type[], 47),
  ('usb', 'USB', array['car']::public.partner_type[], 48),
  ('apple_carplay', 'Apple CarPlay', array['car']::public.partner_type[], 49),
  ('android_auto', 'Android Auto', array['car']::public.partner_type[], 50),
  ('gps', 'GPS', array['car']::public.partner_type[], 51),
  ('camera_arriere', 'Caméra arrière', array['car']::public.partner_type[], 52),
  ('capteurs_parking', 'Capteurs parking', array['car']::public.partner_type[], 53),
  ('4x4_awd', '4x4 / AWD', array['car']::public.partner_type[], 54),
  ('sieges_cuir', 'Sièges cuir', array['car']::public.partner_type[], 55),
  ('toit_ouvrant', 'Toit ouvrant', array['car']::public.partner_type[], 56),
  ('siege_enfant', 'Siège enfant', array['car']::public.partner_type[], 57),
  ('salle_interieure', 'Salle intérieure', array['restaurant']::public.partner_type[], 58),
  ('parking', 'Parking', array['restaurant']::public.partner_type[], 62),
  ('vue_sur_l_eau', 'Vue sur l''eau', array['restaurant']::public.partner_type[], 63),
  ('rooftop', 'Rooftop', array['restaurant']::public.partner_type[], 64),
  ('musique_live', 'Musique live', array['restaurant']::public.partner_type[], 65),
  ('dj', 'DJ', array['restaurant']::public.partner_type[], 66),
  ('famille_bienvenue', 'Famille bienvenue', array['restaurant']::public.partner_type[], 67),
  ('menu_enfants', 'Menu enfants', array['restaurant']::public.partner_type[], 68),
  ('acces_handicape', 'Accès handicapé', array['restaurant']::public.partner_type[], 69),
  ('espace_privatif', 'Espace privatif', array['restaurant']::public.partner_type[], 70),
  ('livraison', 'Livraison', array['restaurant']::public.partner_type[], 71),
  ('a_emporter', 'À emporter', array['restaurant']::public.partner_type[], 72);;
